const models = require('../models')

const populateCoworker = require('./populateCoworker')
const populateProduct = require('./populateProduct')
const populateProblem = require('./populateProblem')
const populateCountry = require('./populateCountry')
const populateSupplier = require('./populateSupplier')
const populateOrder = require('./populateOrder')
const populateClient = require('./populateClient')

models.sequelize.sync({force: true})
    .then(() => console.log("Populate is beginning..."))
    .then(() => console.log("Populating coworkers..."))
    .then(() => populateCoworker())
    .then(() => console.log("Populating countries..."))
    .then(() => populateCountry())
    .then(() => console.log("Populating suppliers..."))
    .then(() => populateSupplier())
    .then(() => console.log("Populating products..."))
    .then(() => populateProduct())
    .then(() => console.log("Populating clients..."))
    .then(() => populateClient())
    .then(() => console.log("Populating orders..."))
    .then(() => populateOrder())
    .then(() => console.log("Populate done."))
.then(() => process.exit(0))
.catch(e => {
  console.log(e);
  process.exit(1);
})
